theme: jekyll-theme-architect
title: Guide for beta-testers
description: Supports qualitative research using audiovisual media & transcripts
URL: "https://bigsoftvideo.github.io/DOTEbase-beta-testing"
image: "/images/logo.png"
markdown: GFM
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - contributing.md
defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"