theme: jekyll-theme-architect
title: Help Guide for Users
description: Supports qualitative research with video & transcripts
URL: "https://bigsoftvideo.github.io/DOTEbase-beta-testing"
image: "/images/logo.png"
markdown: GFM
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - contributing.md
defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"